apiVersion: v1
kind: Secret
metadata:
  name: cinemaabyss-secrets
  namespace: {{ .Values.global.namespace }}
  labels:
    app.kubernetes.io/name: {{ include "cinemaabyss.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
data:
  # Base64 encoded values
  # echo -n "postgres_password" | base64
  DB_PASSWORD: {{ .Values.database.password }}