apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: movies-service
  namespace: cinemaabyss
spec:
  hosts:
    - movies-service
  http:
    - route:
        - destination:
            host: movies-service
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: movies-service
  namespace: cinemaabyss
spec:
  host: movies-service
  trafficPolicy:
    connectionPool:
      tcp:
        maxConnections: 100
      http:
        http1MaxPendingRequests: 50
        maxRequestsPerConnection: 10
    outlierDetection:
      consecutive5xxErrors: 5
      interval: 10s
      baseEjectionTime: 30s
      maxEjectionPercent: 50
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: monolith
  namespace: cinemaabyss
spec:
  hosts:
    - monolith
  http:
    - route:
        - destination:
            host: monolith
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: monolith
  namespace: cinemaabyss
spec:
  host: monolith
  trafficPolicy:
    connectionPool:
      tcp:
        maxConnections: 100
      http:
        http1MaxPendingRequests: 50
        maxRequestsPerConnection: 10
    outlierDetection:
      consecutive5xxErrors: 5
      interval: 10s
      baseEjectionTime: 30s
      maxEjectionPercent: 50