---
# Source: cinemaabyss/templates/services/movies-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: movies-service
  namespace: cinemaabyss
  labels:
    app: movies-service
    app.kubernetes.io/name: cinemaabyss
    app.kubernetes.io/instance: cinemaabyss
spec:
  selector:
    app: movies-service
  ports:
    - port: 8081
      targetPort: 8081
  type: ClusterIP
---
# Source: cinemaabyss/templates/services/movies-service.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: movies-service
  namespace: cinemaabyss
  labels:
    app: movies-service
    app.kubernetes.io/name: cinemaabyss
    app.kubernetes.io/instance: cinemaabyss
spec:
  replicas: 1
  selector:
    matchLabels:
      app: movies-service
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: movies-service
    spec:
      imagePullSecrets:
        - name: dockerconfigjson
      restartPolicy: Always
      containers:
        - name: movies-service
          image: ghcr.io/surrexi/architecture-pro-cinemaabyss/movies-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
          env:
            - name: PORT
              value: "8081"
            - name: DB_CONNECTION_STRING
              value: "postgres://$(DB_USER):$(DB_PASSWORD)@$(DB_HOST):$(DB_PORT)/$(DB_NAME)?sslmode=disable"
          envFrom:
            - configMapRef:
                name: cinemaabyss-config
            - secretRef:
                name: cinemaabyss-secrets
          resources:
            limits:
              cpu: 300m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi
          readinessProbe:
            httpGet:
              path: /api/movies/health
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /api/movies/health
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20
